version: '3.8'

services:
  web:
    image: registry.gitlab.com/jrm-digital/jrm-dev:main
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=public"
        - "traefik.http.routers.jrm_dev.rule=Host(`jrmdev.com.br`)"
        - "traefik.http.routers.jrm_dev.entrypoints=websecure"
        - "traefik.http.services.jrm_dev.loadbalancer.server.port=8000"
        - "traefik.http.routers.jrm_dev.tls.certresolver=myresolver"

networks:
  public:
    external: true


